inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'puppet-languageserver'
  Exclude:
    - 'tmp/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - Gemfile
    - Rakefile
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: '2.7'
# Disabled
Style/ClassAndModuleChildren:
  Enabled: false
