name: "release"

on:
  workflow_dispatch:
    inputs:
      target:
        description: "The target for the release. This can be a commit sha or a branch."
        required: false
        default: "main"
        type: "string"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    if: github.repository_owner == 'puppetlabs'

    steps:

      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          ref: ${{ github.event.inputs.target }}
          clean: true
          fetch-depth: 0

      - name: "Setup ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "2.7"
          bundler-cache: "true"

      - name: "Bundle environment"
        run: |
          echo ::group::bundler environment
          bundle env
          echo ::endgroup::

      - name: "Get version"
        id: "get_version"
        run: |
          echo "version=$(ruby -e "require './lib/puppet_editor_services/version'; puts PuppetEditorServices::PUPPETEDITORSERVICESVERSION.to_s")" >> $GITHUB_OUTPUT

      - name: "Build"
        run: |
          bundle exec rake build

      - name: "Generate release notes"
        run: |
          export GH_HOST=github.com
          gh extension install chelnak/gh-changelog
          gh changelog get --latest > OUTPUT.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Create release"
        run: |
          gh release create v${{ steps.get_version.outputs.version }} ./pkg/* --title v${{ steps.get_version.outputs.version }} -F OUTPUT.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Publish gem to rubygems"
        run: |
          gem push ./pkg/*.gem
        env:
          GEM_HOST_API_KEY: '${{ secrets.GEM_HOST_API_KEY }}'

      - name: "Publish to GitHub Package"
        run: |
          echo "Setting up access to RubyGems"
          mkdir -p ~/.gem
          touch ~/.gem/credentials
          chmod 600 ~/.gem/credentials

          echo "Logging in to GitHub Package Registry"
          echo "---" > ~/.gem/credentials
          echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" >> ~/.gem/credentials

          echo "Pushing gem to GitHub Package Registry"
          gem push --key "github" --host "https://rubygems.pkg.github.com/${{github.repository_owner}}" ./pkg/*.gem
